### ISSUE TITLE
Entrevista a un ING. sobre la Gestión de Proyectos

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/entrevista-entrevista-mitte#2]
[Entrevista Gestion de proyectos.pdf](https://github.com/SistemasTecTlaxiaco/entrevista-entrevista-mitte/files/7156520/Entrevista.Gestion.de.proyectos.pdf)

Link de la entrevista: https://www.youtube.com/watch?v=wxoHlFNzBIg

**Comment by MaGuadalupeQuiroz** [comment]
Muy buen trabajo, las preguntas son interesantes.
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
